language: node_js
node_js:
    - "6"
deploy:
  provider: heroku
  app: powerful-plateau-78327
  api_key:
    secure: YBoeP/3n9hXtx9JDIMMXnpBCuJdu/J7dn3eh3ymptTbROV2oWjiYKbNS9dOFH4alkydUIVXUN0nNO3D5ugfMwq+W2NB4xjdRbdOzUEiq3BcbbsxOYlDoISbCMjY3/XCLQ1BNug9Z7UjQqPIOqzR/u1h9c4fRqOxyHSv4zrZkGYadM8bOHndEZSHRzzkhauM2JeLLpWxMd58KAcQNDJCz9Y4lplpBnqIfqOM3S2BqDuGTFY1nAKXF7leRshbpUUdSxo3Y6FCal9tfUhKBX8AbiYVe4ASZ3Fqjg5hZWyFpzvrbmupFj6L7NZnQhOhv2GizpOFEEyCo9RBPbd4EWi2cCe0HPceEO9dyiRt1i+bpO/w1qkNeBYwk8AkBxhD78RVPiYJHrXdzwDOp1kixFKi85owaBqWaKxfV3PhLUb1DiRuhUGqapNJtJxnbnv74GD7amoGTf1eafhXKXUIq1t0x4qbKhoAMJHWr98TvUQ06fIie62c0mXLIk4oyJQKO+NlyjLE1mKoYcJSD38PbCYX7RScf7wHtdP+Bp2P2fc3zP0RgtCu6bRWuIysisQhsPcQn0E72mxDIR6SInCqftRKF0HnkMZQ/l0uf+DpcBc/wVLaBCRdKmE/gCgj7zdlrhmiqPTrtdGpdLRWuVwLx3+HSI9QEWqXUCO4Gx/0pRTyPcME=
  before_script:
    - npm install
  script:
    - node server.js
