language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  app: powerful-plateau-78327
  api_key:
    secure: Fx0xIdlg9WlC7SkGc8wNLwtKijz0xnjtl4+y7VwK+l5Had1mt5kVj99a7WqjK4QecHy7kxZxZgb66ZZkXcnUmuC+XbznXYDpp4c9V74dllnISoLlAUfaPf/yYoPBG1EwFsUU6QYt9KQXolYDk/A4JXNCeoDte2UbUq9JlyCzFyoQeJJ1W7wsDT/rXjziVHsxsAtHuPIFELpTDfPMcu16BOpEKsM4uRVmB/hWI3YW0Q5jViZlt2hkviSoGBrTtYOuDdTnY/cFSPZf7GpU27py8aTl+VmKAWYwaT7ohpc0m+0NoF+j3GCV3fONncLkJcF0iIwWE3Jx/loibHD0n15pZKmdlrTGqy3Ffob/x/9GWIH+06m7BT6H3E6Cw+buQCpgi/eYCUlcQBRYx1bB+3vEFbFAIav+SHLeVj1jhtwNYwW0tfQfFYm5xm88OS9Pr8ZT+4WuoyRp/ywGFGIlkCScf0N+9MyIUa3wk/HW5ydvDCEOsCNeSIda3n1ZJ23U+/M+0ckPRGOWc+0csfcXEGkX+NXYn3v+AwREOW7Bm06MzCs46Z9rCm2Cjeb7vfLTmMvsyZsMfJzCa5+R8OCkSuxFlyPHsdOLtiAzAEENSfJxWAd0jMsd/YI0RSeZMY8ucboYfBOC6pF30SuVZB6qS2DYL8z+nyJgUaa3ICyyRBqth5Y=
  before_script:
  - npm install
  script:
  - node server.js
